### ISSUE TITLE
Useragent is very unique

### ISSUE THREAD

**Issue by CactiChameleon9** [nicolascolla/onion-surf#1]
I know this isn't meant to be anonymous, however making improvements to reduce fingerprinting seems like a good thing.
Currently, the default useragent is very device specific and gives a lot of data - making it a massive factor in the fingerprint (screenshot attached)
Therefore I think a static useragent should be set for all users (tor browser mobile probably makes the most sense)

![screenshot20211014_205250732](https://user-images.githubusercontent.com/51231053/137386374-42b0390d-e151-4f33-91ad-b1b82c6ece68.png)

**Comment by nicolascolla** [comment]
This issue and the WebRTC IP leak are the highest-priority fixes for now. While some hardcoded QtWebEngine flags work, others (like the flag supposed to fix the WebRTC problem) do not. It will be easy to specify either the Tor mobile or the Tor desktop useragent with a flag once this is fixed.

**Comment by nicolascolla** [comment]
Fixed with no custom flags necessary: https://github.com/nicolascolla/onion-surf/commit/fd8328c5f7564ff63c5ac624a3868bffd2a399f1

**Comment by CactiChameleon9** [comment]
Wow, that was quick. Thanks 👍

**Comment by CactiChameleon9** [comment]
Just a note: the webrtc leak doesn't seem too bad as its only leaking my local ip not my public one.

**Comment by gbdomubpkm** [comment]
Hello @nicolascolla 
Thanks for all your investment in this challenge to make Tor work well on UT.
Just as a reminder about WebRTC leak, in case you don't know (probably not 😉 ), I'm attaching this pull request https://github.com/nanu-c/onion-browser/pull/3 if it's of any use to you.

**Comment by nicolascolla** [comment]
> Hello @nicolascolla Thanks for all your investment in this challenge to make Tor work well on UT. Just as a reminder about WebRTC leak, in case you don't know (probably not wink ), I'm attaching this pull request [nanu-c#3](https://github.com/nanu-c/onion-browser/pull/3) if it's of any use to you.

I am aware of the commit and it has been merged here (https://github.com/nicolascolla/onion-surf/commit/f495953008857612e2d574a805e9bbb5ab5c153c). However, it didn't work (something was probably overriding the flag, https://github.com/nicolascolla/onion-surf/commit/67aafefc718f1c228e13a1c4da4cd220599d457a fixes it) and what the flag does is just hide your local IP; the public IP is still leaking.

The only solutions I can think of are:

1. Disabling WebRTC with a js injection (messy and unreliable)
2. Recompiling QtWebEngine with WebRTC disabled (time-consuming and would probably conflict with other apps).

**Comment by gbdomubpkm** [comment]
Nothing to do with invisibility, but I'd like to point out here (as i don't know where to do that) this positive point of your morph-based browser: on the Volla, scrolling web pages of a link is never jerky, whereas it can be the case with morph-browser if you don't allow enough latency for the link to load properly. For example with this link: https://www.pine64.org/pinephonepro/ : on morph, there is a kind of memory that makes the scrolling always jerky for the scrolling of all the data of the link.
Did you do anything different than on morph-browser to make the scrolling work so well on Onion?
