### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by nicolascolla** [nicolascolla/onion-surf#3]
The browser does not route DNS requests through the SOCKS proxy, and the flag necessary to do that (`--host-resolver-rules`) is only available in QtWebEngine 5.15 onwards (current version: 5.14.2).

**Comment by gbdomubpkm** [comment]
UBports OTA-23 should upgrade QtWebengine to 5.15.9
https://gitlab.com/ubports/core/packaging/qtwebengine/-/merge_requests/8

**Comment by nicolascolla** [comment]
The readme has been updated.
